### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by heruisi** [paddle-python/paddle-client#1]
Hello, I am from Baidu PaddlePaddle team. I learned from giuhub that you have begun to use PaddlePaddle and we would like to offer you more support including technical help and others. Would you like to join PaddlePaddle community and have fun? If interested, you can conntact me via Wechat, my ID is paddlehelp, or you can contact me via email v_heruisi@baidu.com. Looking forward to your reply :)

Looking forward to your reply~

**Comment by pyepye** [comment]
Hi @heruisi 

I think there has been a little bit of a mixup. This repo is a client for [Paddle.com](https://paddle.com/) API and not PaddlePaddle.

Sorry about that and good luck with the PaddlePaddle community
