### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by slado122** [paddle-python/paddle-client#5]
It's not really clear how to create a subscription and let a user approve it. I see there are only `update_subscription` and `cancel_subscription`. So how can I create a subscription first? A code sample would be appreciated.

**Comment by pyepye** [comment]
Hi @slado122 

This reply is a little late as I missed the Github notification, sorry about that.

I don't believe it's possible to create subscriptions or take payments via the Paddle API which by extension means it's not possible to do so via this wrapper.

The best way to allow a user to create and pay for a subscription is using the [Paddle Checkout](https://developer.paddle.com/guides/how-tos/checkout/paddle-checkout). Hopefully the application you are making is either web based or supports Javascript.

If you are using Django check out [dj-paddle](https://github.com/paddle-python/dj-paddle) which helps you both setup the Paddle Checkout as well as helps create endpoints for paddle webhooks.

Hope that helps.

Matt

**Comment by slado122** [comment]
Thanks a lot.
